# See https://wiki.hypr.land/Configuring/Environment-variables/
# You will have to change some of these environment variables if you have an AMD card (or an integrated GPU).
# I highly recommend checking the Hyprland wiki to see how to properly install the right drivers for your GPU (especially if you have an Nvidia card).

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = COPYQ_DEFAULT_ICON=1,copyq
env = COPYQ_SESSION_COLOR="#ffffff",copyq
env = GTK_THEME=catppuccin-mocha
env = MOZ_ENABLE_WAYLAND=1

# qt settings
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct

# other
env = EDITOR,micro
